services:
    smile.import_from_multi_ez4_to_platform.initial_import_helper:
        class: Smile\ImportFromMultiEZ4toPlatformBundle\Helper\InitialImportHelper
        arguments:
           - @service_container
           - @ezpublish.api.repository
